version: '3.8'

include:
  - proxy.yaml  # Подключаем существующую конфигурацию прокси

services:
  web:
    build:
      context: .  # Собираем из Dockerfile.python
      dockerfile: Dockerfile.python
    networks:
      backend:
        ipv4_address: 172.20.0.5  # Фиксированный IP
    environment:
      DB_HOST: db  # Используем имя сервиса для подключения
      DB_USER: ${MYSQL_USER}  # Из .env
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    restart: always  # Автоперезапуск
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8
    networks:
      backend:
        ipv4_address: 172.20.0.10  # Фиксированный IP
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:  # Для корректного depends_on
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  backend:  # Сеть из proxy.yaml
    external: true

volumes:
  mysql_data:
